### ISSUE TITLE
Allow tests to be skipped

### ISSUE THREAD

**Issue by lloydk** [LeaVerou/htest#12]
As mentioned in color-js/color.js#428 it would be nice if tests could be skipped.

This could be as simple as adding a `skip` property to a test or set of tests. E.g. 

```javascript
{
	name: "hwb()",
	skip: "hwb color space not implemented yet",
	tests: [
		{
			args: "hwb(180 20% 30%)",
			expect: '{"spaceId":"hwb","coords":[180,20,30],"alpha":1}'
		},
	]
}
```

The test runners would output the number of skipped tests.

**Comment by LeaVerou** [comment]
Hey @lloydk, I’ve started working on this and I had a question: how did you envision the value of `skip` to be used? I thought it would just print something like "1/6 skipped".

**Comment by LeaVerou** [comment]
Ok, I pushed an experimental implementation, would love it if you could try it and give me feedback! (hasn't published to npm yet though)

**Comment by lloydk** [comment]
It would be nice if the skip property was inherited so I could easily skip a group of tests. Or be able to set it at the top level of a test file and then set a specific test to `skip: false` to have only a single test run (useful for debugging).

I would use `yellow` instead of `dim` for the output but that's just my personal preference.

**Comment by LeaVerou** [comment]
It was meant to be inherited! If it's not, that's a bug!

**Comment by LeaVerou** [comment]
Have you tried it and it does not inherit?

**Comment by lloydk** [comment]
> Have you tried it and it does not inherit?

I tried it and it didn't work

**Comment by LeaVerou** [comment]
Ah bummer. Can you open an issue about that bug?

**Comment by lloydk** [comment]
> Ah bummer. Can you open an issue about that bug?

Created a PR #15, it was a simple fix.
