### ISSUE TITLE
Allow specific files to be skipped

### ISSUE THREAD

**Issue by adamjanicki2** [LeaVerou/htest#14]
It would be useful if there was a way to ignore specific files. For example, if there's a helper file in a test directory that doesn't contain tests, specifying to htest to ignore that file would be useful

**Comment by LeaVerou** [comment]
Right now the only way to do that is to run `htest <glob>` instead of `htest`, but perhaps there could be an `.htestignore` file with syntax similar to `.gitignore`/`.npmignore`/`.eleventyignore` etc. to facilitate this?

**Comment by LeaVerou** [comment]
On second thought, I think this is a duplicate of #4, since we can set that there. Probably overkill to have a whole file just for excluding at this point.
