### ISSUE TITLE
Return a non-zero exit code if there are failing tests

### ISSUE THREAD

**Issue by lloydk** [LeaVerou/htest#16]
The cli should return a non-zero exit code if there are failing tests. This will make it easier to integrate htest into CI environments.

**Comment by LeaVerou** [comment]
Oh good catch! Wanna submit a PR?

**Comment by lloydk** [comment]
> Oh good catch! Wanna submit a PR?

#17

**Comment by LeaVerou** [comment]
Closed via #17 (though I'm making a few other changes before releasing a new version).
