### ISSUE TITLE
`expect` is not inheritable

### ISSUE THREAD

**Issue by DmitrySharabin** [LeaVerou/htest#18]
Per [our docs](https://htest.dev/docs/define/js/), any test properties set on a group will be inherited by the group's tests.

Unfortunately, `expect` is not the case yet, so this example from [Quick start](https://htest.dev/#quick-start) doesn't work.

```js
import { sum } from "../src/util.js";

export default {
	name: "With NaN",
	run (...args) {
		return sum(NaN, ...args);
	},
	expect: NaN,
	tests: [
		{
			args: [1, 2, 3],
		},
		{
			args: [],
		},
		{
			args: [NaN]
		}
	]
}
```

I checked, and it looks like to fix it, we can simply add `expect` to the array here:

https://github.com/LeaVerou/htest/blob/83f35aeeb3c31a68f05d3030c4ff006b5071de9a/src/js/classes/Test.js#L32

```diff
- for (let prop of ["run", "map", "check", "getName", "args", "skip"]) {
+ for (let prop of ["run", "map", "check", "getName", "args", "expect", "skip"]) {
```

I am ready to submit a PR with the fix if there is nothing wrong with the proposed one.

**Comment by LeaVerou** [comment]
Sounds good, thanks!
