### ISSUE TITLE
`deep()` throws if `actual` is either `null` or `undefined`

### ISSUE THREAD

**Issue by DmitrySharabin** [LeaVerou/htest#19]
It happens on this line if we compare objects recursively:

https://github.com/LeaVerou/htest/blob/6a708285f955b1bcf0df6cf49a9879cad361a000/src/check.js#L86

### `actual`

```
{
  url: URL {
    href: "local:foo",
    origin: "null",
    protocol: "local:",
    username: "",
    password: "",
    host: "",
    hostname: "",
    port: "",
    pathname: "foo",
    search: "",
    searchParams: URLSearchParams {},
    hash: ""
  },
  key: "foo"
}
```

### `expected`

```
{
  key: "foo"
}
```

**Comment by LeaVerou** [comment]
Eeek, that's bad. Can you still repro?

**Comment by DmitrySharabin** [comment]
> Can you still repro?

I can't.  Looks like you already fixed it. Yay! 🥳
