### ISSUE TITLE
JS-first tests: Is there value in objects being able to be *both* tests *and* groups?

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/htest#2]
Right now, depending on the presence of certain keys, an object literal can be either a test, or a group of tests, or both.
The fluidity is nice, since it's common to start with a simple test and eventually expand it to more granular tests. However, when you do that, you'd typically convert the initial test to a group, with the initial test as its first child. It's not natural to have the group *be* a test as well. It increases complexity significantly, with no actual use cases to support it.

I’m leaning towards a much simpler model where an object is either a group of tests (if it has a `tests` array) or a single test. 

Not only would this simplify logic in many places, it would also open the door to doing things like e.g. args being semi-inherited, with args on groups being added to the end of their child tests, which currently requires `data`.

Any objections?

Edit: I think I will actually make the change, but can always roll back if there are good arguments for the current model.

**Comment by adamjanicki2** [comment]
I really like this, first of all, at a high level, it matches the design of other js testing frameworks like jest which have the ability to create groups of test cases that all focus on one thing (see [here](https://stackoverflow.com/questions/32055287/what-is-the-difference-between-describe-and-it-in-jest)). The simplicity of having the `tests` field set is nice versus a more ambiguous way of specifying if it is a group or not

**Comment by adamjanicki2** [comment]
Yeah I understood what you meant, I was saying that I like the original idea of having groups in the first place, and making this change that deduplicates functionality is a good thing because it's confusing something could be both
