### ISSUE TITLE
Interactive tree for CLI output

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/htest#23]
One of the primary blockers for launch is the CLI output.

Not only bugs like #7, but in general a re-architecting of the CLI output to make it more usable and take better advantage of hTest’s hierarchical structure.

My current thinking is something like this:
- By default, the whole tree is collapsed
- Users can navigate with the arrow keys to select parts of the tree and hit the right arrow key to expand them (and the left arrow key to collapse them) to see test failures and stats for subgroups
- Unsure how this would work if the tree is longer than the terminal window 🤔

**Comment by DmitrySharabin** [comment]
Suppose we decide that [this tool](https://fx.wtf/) might help solve this issue. In that case, it might be beneficial to have the output (protocol of tests execution) in JSON format, which we can pass to `fx` and let the user view it interactively, download it, or do whatever they need. 🤔

**Comment by LeaVerou** [comment]
No, it would absolutely not be helpful to output JSON!
I just thought it may help to look at how fx does it so that we can do the same thing. Not use fx, it's not even written in JS!
