### ISSUE TITLE
Command line All Tests Pass/Fail count

### ISSUE THREAD

**Issue by lloydk** [LeaVerou/htest#8]
It would be nice to have the count of passing and failing tests at the end of the cli output. Right now I have to scroll to top of the tree to see the counts.

**Comment by LeaVerou** [comment]
Oh that's an excellent point!

I wish it were possible to make the tree interactive (with arrow keys), with it being collapsed by default. That would solve both this, and #7 and improve usability tremendously in one fell swoop. But it seems so hard to do it and there's no existing package for this.

**Comment by LeaVerou** [comment]
I just opened #23 to track this. Since once #23 is addressed, this will be fixed too, I'm going to close this as a dupe.
